# CMAKE generated file: DO NOT EDIT!
# Generated by "MinGW Makefiles" Generator, CMake Version 3.4

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Produce verbose output by default.
VERBOSE = 1

# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

SHELL = cmd.exe

# The CMake executable.
CMAKE_COMMAND = "C:\Program Files (x86)\CMake\bin\cmake.exe"

# The command to remove a file.
RM = "C:\Program Files (x86)\CMake\bin\cmake.exe" -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = C:\Users\Pichau\AndroidStudioProjects\yoga

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = C:\Users\Pichau\AndroidStudioProjects\yoga

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	"C:\Program Files (x86)\CMake\bin\cmake-gui.exe" -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	"C:\Program Files (x86)\CMake\bin\cmake.exe" -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start C:\Users\Pichau\AndroidStudioProjects\yoga\CMakeFiles C:\Users\Pichau\AndroidStudioProjects\yoga\CMakeFiles\progress.marks
	$(MAKE) -f CMakeFiles\Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start C:\Users\Pichau\AndroidStudioProjects\yoga\CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles\Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named yogacore

# Build rule for target.
yogacore: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 yogacore
.PHONY : yogacore

# fast build rule for target.
yogacore/fast:
	$(MAKE) -f CMakeFiles\yogacore.dir\build.make CMakeFiles/yogacore.dir/build
.PHONY : yogacore/fast

yoga/Utils.obj: yoga/Utils.cpp.obj

.PHONY : yoga/Utils.obj

# target to build an object file
yoga/Utils.cpp.obj:
	$(MAKE) -f CMakeFiles\yogacore.dir\build.make CMakeFiles/yogacore.dir/yoga/Utils.cpp.obj
.PHONY : yoga/Utils.cpp.obj

yoga/Utils.i: yoga/Utils.cpp.i

.PHONY : yoga/Utils.i

# target to preprocess a source file
yoga/Utils.cpp.i:
	$(MAKE) -f CMakeFiles\yogacore.dir\build.make CMakeFiles/yogacore.dir/yoga/Utils.cpp.i
.PHONY : yoga/Utils.cpp.i

yoga/Utils.s: yoga/Utils.cpp.s

.PHONY : yoga/Utils.s

# target to generate assembly for a file
yoga/Utils.cpp.s:
	$(MAKE) -f CMakeFiles\yogacore.dir\build.make CMakeFiles/yogacore.dir/yoga/Utils.cpp.s
.PHONY : yoga/Utils.cpp.s

yoga/YGConfig.obj: yoga/YGConfig.cpp.obj

.PHONY : yoga/YGConfig.obj

# target to build an object file
yoga/YGConfig.cpp.obj:
	$(MAKE) -f CMakeFiles\yogacore.dir\build.make CMakeFiles/yogacore.dir/yoga/YGConfig.cpp.obj
.PHONY : yoga/YGConfig.cpp.obj

yoga/YGConfig.i: yoga/YGConfig.cpp.i

.PHONY : yoga/YGConfig.i

# target to preprocess a source file
yoga/YGConfig.cpp.i:
	$(MAKE) -f CMakeFiles\yogacore.dir\build.make CMakeFiles/yogacore.dir/yoga/YGConfig.cpp.i
.PHONY : yoga/YGConfig.cpp.i

yoga/YGConfig.s: yoga/YGConfig.cpp.s

.PHONY : yoga/YGConfig.s

# target to generate assembly for a file
yoga/YGConfig.cpp.s:
	$(MAKE) -f CMakeFiles\yogacore.dir\build.make CMakeFiles/yogacore.dir/yoga/YGConfig.cpp.s
.PHONY : yoga/YGConfig.cpp.s

yoga/YGEnums.obj: yoga/YGEnums.cpp.obj

.PHONY : yoga/YGEnums.obj

# target to build an object file
yoga/YGEnums.cpp.obj:
	$(MAKE) -f CMakeFiles\yogacore.dir\build.make CMakeFiles/yogacore.dir/yoga/YGEnums.cpp.obj
.PHONY : yoga/YGEnums.cpp.obj

yoga/YGEnums.i: yoga/YGEnums.cpp.i

.PHONY : yoga/YGEnums.i

# target to preprocess a source file
yoga/YGEnums.cpp.i:
	$(MAKE) -f CMakeFiles\yogacore.dir\build.make CMakeFiles/yogacore.dir/yoga/YGEnums.cpp.i
.PHONY : yoga/YGEnums.cpp.i

yoga/YGEnums.s: yoga/YGEnums.cpp.s

.PHONY : yoga/YGEnums.s

# target to generate assembly for a file
yoga/YGEnums.cpp.s:
	$(MAKE) -f CMakeFiles\yogacore.dir\build.make CMakeFiles/yogacore.dir/yoga/YGEnums.cpp.s
.PHONY : yoga/YGEnums.cpp.s

yoga/YGLayout.obj: yoga/YGLayout.cpp.obj

.PHONY : yoga/YGLayout.obj

# target to build an object file
yoga/YGLayout.cpp.obj:
	$(MAKE) -f CMakeFiles\yogacore.dir\build.make CMakeFiles/yogacore.dir/yoga/YGLayout.cpp.obj
.PHONY : yoga/YGLayout.cpp.obj

yoga/YGLayout.i: yoga/YGLayout.cpp.i

.PHONY : yoga/YGLayout.i

# target to preprocess a source file
yoga/YGLayout.cpp.i:
	$(MAKE) -f CMakeFiles\yogacore.dir\build.make CMakeFiles/yogacore.dir/yoga/YGLayout.cpp.i
.PHONY : yoga/YGLayout.cpp.i

yoga/YGLayout.s: yoga/YGLayout.cpp.s

.PHONY : yoga/YGLayout.s

# target to generate assembly for a file
yoga/YGLayout.cpp.s:
	$(MAKE) -f CMakeFiles\yogacore.dir\build.make CMakeFiles/yogacore.dir/yoga/YGLayout.cpp.s
.PHONY : yoga/YGLayout.cpp.s

yoga/YGNode.obj: yoga/YGNode.cpp.obj

.PHONY : yoga/YGNode.obj

# target to build an object file
yoga/YGNode.cpp.obj:
	$(MAKE) -f CMakeFiles\yogacore.dir\build.make CMakeFiles/yogacore.dir/yoga/YGNode.cpp.obj
.PHONY : yoga/YGNode.cpp.obj

yoga/YGNode.i: yoga/YGNode.cpp.i

.PHONY : yoga/YGNode.i

# target to preprocess a source file
yoga/YGNode.cpp.i:
	$(MAKE) -f CMakeFiles\yogacore.dir\build.make CMakeFiles/yogacore.dir/yoga/YGNode.cpp.i
.PHONY : yoga/YGNode.cpp.i

yoga/YGNode.s: yoga/YGNode.cpp.s

.PHONY : yoga/YGNode.s

# target to generate assembly for a file
yoga/YGNode.cpp.s:
	$(MAKE) -f CMakeFiles\yogacore.dir\build.make CMakeFiles/yogacore.dir/yoga/YGNode.cpp.s
.PHONY : yoga/YGNode.cpp.s

yoga/YGNodePrint.obj: yoga/YGNodePrint.cpp.obj

.PHONY : yoga/YGNodePrint.obj

# target to build an object file
yoga/YGNodePrint.cpp.obj:
	$(MAKE) -f CMakeFiles\yogacore.dir\build.make CMakeFiles/yogacore.dir/yoga/YGNodePrint.cpp.obj
.PHONY : yoga/YGNodePrint.cpp.obj

yoga/YGNodePrint.i: yoga/YGNodePrint.cpp.i

.PHONY : yoga/YGNodePrint.i

# target to preprocess a source file
yoga/YGNodePrint.cpp.i:
	$(MAKE) -f CMakeFiles\yogacore.dir\build.make CMakeFiles/yogacore.dir/yoga/YGNodePrint.cpp.i
.PHONY : yoga/YGNodePrint.cpp.i

yoga/YGNodePrint.s: yoga/YGNodePrint.cpp.s

.PHONY : yoga/YGNodePrint.s

# target to generate assembly for a file
yoga/YGNodePrint.cpp.s:
	$(MAKE) -f CMakeFiles\yogacore.dir\build.make CMakeFiles/yogacore.dir/yoga/YGNodePrint.cpp.s
.PHONY : yoga/YGNodePrint.cpp.s

yoga/YGStyle.obj: yoga/YGStyle.cpp.obj

.PHONY : yoga/YGStyle.obj

# target to build an object file
yoga/YGStyle.cpp.obj:
	$(MAKE) -f CMakeFiles\yogacore.dir\build.make CMakeFiles/yogacore.dir/yoga/YGStyle.cpp.obj
.PHONY : yoga/YGStyle.cpp.obj

yoga/YGStyle.i: yoga/YGStyle.cpp.i

.PHONY : yoga/YGStyle.i

# target to preprocess a source file
yoga/YGStyle.cpp.i:
	$(MAKE) -f CMakeFiles\yogacore.dir\build.make CMakeFiles/yogacore.dir/yoga/YGStyle.cpp.i
.PHONY : yoga/YGStyle.cpp.i

yoga/YGStyle.s: yoga/YGStyle.cpp.s

.PHONY : yoga/YGStyle.s

# target to generate assembly for a file
yoga/YGStyle.cpp.s:
	$(MAKE) -f CMakeFiles\yogacore.dir\build.make CMakeFiles/yogacore.dir/yoga/YGStyle.cpp.s
.PHONY : yoga/YGStyle.cpp.s

yoga/YGValue.obj: yoga/YGValue.cpp.obj

.PHONY : yoga/YGValue.obj

# target to build an object file
yoga/YGValue.cpp.obj:
	$(MAKE) -f CMakeFiles\yogacore.dir\build.make CMakeFiles/yogacore.dir/yoga/YGValue.cpp.obj
.PHONY : yoga/YGValue.cpp.obj

yoga/YGValue.i: yoga/YGValue.cpp.i

.PHONY : yoga/YGValue.i

# target to preprocess a source file
yoga/YGValue.cpp.i:
	$(MAKE) -f CMakeFiles\yogacore.dir\build.make CMakeFiles/yogacore.dir/yoga/YGValue.cpp.i
.PHONY : yoga/YGValue.cpp.i

yoga/YGValue.s: yoga/YGValue.cpp.s

.PHONY : yoga/YGValue.s

# target to generate assembly for a file
yoga/YGValue.cpp.s:
	$(MAKE) -f CMakeFiles\yogacore.dir\build.make CMakeFiles/yogacore.dir/yoga/YGValue.cpp.s
.PHONY : yoga/YGValue.cpp.s

yoga/Yoga.obj: yoga/Yoga.cpp.obj

.PHONY : yoga/Yoga.obj

# target to build an object file
yoga/Yoga.cpp.obj:
	$(MAKE) -f CMakeFiles\yogacore.dir\build.make CMakeFiles/yogacore.dir/yoga/Yoga.cpp.obj
.PHONY : yoga/Yoga.cpp.obj

yoga/Yoga.i: yoga/Yoga.cpp.i

.PHONY : yoga/Yoga.i

# target to preprocess a source file
yoga/Yoga.cpp.i:
	$(MAKE) -f CMakeFiles\yogacore.dir\build.make CMakeFiles/yogacore.dir/yoga/Yoga.cpp.i
.PHONY : yoga/Yoga.cpp.i

yoga/Yoga.s: yoga/Yoga.cpp.s

.PHONY : yoga/Yoga.s

# target to generate assembly for a file
yoga/Yoga.cpp.s:
	$(MAKE) -f CMakeFiles\yogacore.dir\build.make CMakeFiles/yogacore.dir/yoga/Yoga.cpp.s
.PHONY : yoga/Yoga.cpp.s

yoga/event/event.obj: yoga/event/event.cpp.obj

.PHONY : yoga/event/event.obj

# target to build an object file
yoga/event/event.cpp.obj:
	$(MAKE) -f CMakeFiles\yogacore.dir\build.make CMakeFiles/yogacore.dir/yoga/event/event.cpp.obj
.PHONY : yoga/event/event.cpp.obj

yoga/event/event.i: yoga/event/event.cpp.i

.PHONY : yoga/event/event.i

# target to preprocess a source file
yoga/event/event.cpp.i:
	$(MAKE) -f CMakeFiles\yogacore.dir\build.make CMakeFiles/yogacore.dir/yoga/event/event.cpp.i
.PHONY : yoga/event/event.cpp.i

yoga/event/event.s: yoga/event/event.cpp.s

.PHONY : yoga/event/event.s

# target to generate assembly for a file
yoga/event/event.cpp.s:
	$(MAKE) -f CMakeFiles\yogacore.dir\build.make CMakeFiles/yogacore.dir/yoga/event/event.cpp.s
.PHONY : yoga/event/event.cpp.s

yoga/internal/experiments.obj: yoga/internal/experiments.cpp.obj

.PHONY : yoga/internal/experiments.obj

# target to build an object file
yoga/internal/experiments.cpp.obj:
	$(MAKE) -f CMakeFiles\yogacore.dir\build.make CMakeFiles/yogacore.dir/yoga/internal/experiments.cpp.obj
.PHONY : yoga/internal/experiments.cpp.obj

yoga/internal/experiments.i: yoga/internal/experiments.cpp.i

.PHONY : yoga/internal/experiments.i

# target to preprocess a source file
yoga/internal/experiments.cpp.i:
	$(MAKE) -f CMakeFiles\yogacore.dir\build.make CMakeFiles/yogacore.dir/yoga/internal/experiments.cpp.i
.PHONY : yoga/internal/experiments.cpp.i

yoga/internal/experiments.s: yoga/internal/experiments.cpp.s

.PHONY : yoga/internal/experiments.s

# target to generate assembly for a file
yoga/internal/experiments.cpp.s:
	$(MAKE) -f CMakeFiles\yogacore.dir\build.make CMakeFiles/yogacore.dir/yoga/internal/experiments.cpp.s
.PHONY : yoga/internal/experiments.cpp.s

yoga/log.obj: yoga/log.cpp.obj

.PHONY : yoga/log.obj

# target to build an object file
yoga/log.cpp.obj:
	$(MAKE) -f CMakeFiles\yogacore.dir\build.make CMakeFiles/yogacore.dir/yoga/log.cpp.obj
.PHONY : yoga/log.cpp.obj

yoga/log.i: yoga/log.cpp.i

.PHONY : yoga/log.i

# target to preprocess a source file
yoga/log.cpp.i:
	$(MAKE) -f CMakeFiles\yogacore.dir\build.make CMakeFiles/yogacore.dir/yoga/log.cpp.i
.PHONY : yoga/log.cpp.i

yoga/log.s: yoga/log.cpp.s

.PHONY : yoga/log.s

# target to generate assembly for a file
yoga/log.cpp.s:
	$(MAKE) -f CMakeFiles\yogacore.dir\build.make CMakeFiles/yogacore.dir/yoga/log.cpp.s
.PHONY : yoga/log.cpp.s

# Help Target
help:
	@echo The following are some of the valid targets for this Makefile:
	@echo ... all (the default if no target is provided)
	@echo ... clean
	@echo ... depend
	@echo ... edit_cache
	@echo ... yogacore
	@echo ... rebuild_cache
	@echo ... yoga/Utils.obj
	@echo ... yoga/Utils.i
	@echo ... yoga/Utils.s
	@echo ... yoga/YGConfig.obj
	@echo ... yoga/YGConfig.i
	@echo ... yoga/YGConfig.s
	@echo ... yoga/YGEnums.obj
	@echo ... yoga/YGEnums.i
	@echo ... yoga/YGEnums.s
	@echo ... yoga/YGLayout.obj
	@echo ... yoga/YGLayout.i
	@echo ... yoga/YGLayout.s
	@echo ... yoga/YGNode.obj
	@echo ... yoga/YGNode.i
	@echo ... yoga/YGNode.s
	@echo ... yoga/YGNodePrint.obj
	@echo ... yoga/YGNodePrint.i
	@echo ... yoga/YGNodePrint.s
	@echo ... yoga/YGStyle.obj
	@echo ... yoga/YGStyle.i
	@echo ... yoga/YGStyle.s
	@echo ... yoga/YGValue.obj
	@echo ... yoga/YGValue.i
	@echo ... yoga/YGValue.s
	@echo ... yoga/Yoga.obj
	@echo ... yoga/Yoga.i
	@echo ... yoga/Yoga.s
	@echo ... yoga/event/event.obj
	@echo ... yoga/event/event.i
	@echo ... yoga/event/event.s
	@echo ... yoga/internal/experiments.obj
	@echo ... yoga/internal/experiments.i
	@echo ... yoga/internal/experiments.s
	@echo ... yoga/log.obj
	@echo ... yoga/log.i
	@echo ... yoga/log.s
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 0
.PHONY : cmake_check_build_system

