name: yoga_engine
description: A plugin that uses yoga to implements flexbox layout in Flutter.
version: 0.0.5
homepage: https://github.com/ZupIT/yoga/tree/master/flutter

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  get_it: ^7.2.0

dev_dependencies:
  build_runner: ^2.0.6
  ffigen: ^3.0.0
  flutter_test:
    sdk: flutter
  lints: ^1.0.1
  mockito: ^5.0.12

ffigen:
  name: Yoga
  description: Bindings to `yoga/Yoga.h`.
  output: 'generated_bindings.dart'
  headers:
    entry-points:
      - '../yoga/Yoga.h'

flutter:
  plugin:
    platforms:
      android:
        package: br.com.zup.yoga_engine
        pluginClass: YogaEnginePlugin
      ios:
        pluginClass: YogaEnginePlugin
